<a href="https://colab.research.google.com/github/albaMCh/Numpy/blob/main/Proyecto_Final_Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Singular Value Descomposition (SVD) con Numpy

La factorización de matrices o descomposición de matrices consiste en describir una matriz utilizando sus elementos constitutivos. El método más conocido y utilizado para esta factorización matricial es la descomposición en valores singulares. Se utiliza para la compresión, eliminación de ruido, reducción de datos...

**IMPORTANTE:** si te aparece el error 'TruncatedSVD' object is not callable reinicia el entorno de ejecución y ejecuta todas las celdas de nuevo (puedes hacer esto desde el menú de entorno de ejecucción de la barra superior o pulsando Ctrl+ M + . y después Ctrl+ F9).



##Descomposicion en valores singulares (SVD)

Una matriz A de m filas y n columnas se puede descomponer en:
* Matirz U (m x m)
* Matriz Sigma (m x n diagonal)
* Matriz V^T o V transpuesta (n x n )

      A(m x n)= U (m x m) . Sigma (m x n) . V^T (n x n)

Donde los elementos de la diagonal de la matriz sigma son los valores singulares, las columnas de la matriz U son los vectores singulares izquierdos de A (left-singular vectors) y las columnas de la matriz V son los vectores singulares derechos de A (rigth-singular vectors)

Se pueden obtener las matrices U, sigma y V^T importando la funcion svd del módulo numpy.linalg.



Crea la función calcular_svd que tomando una matriz como parámetro devuelva un diccionario que contenga las claves 'U', 's' y 'V_T' y su respectiva matriz como valor.


Ejemplo 

dada la matriz A:

      [[1 2]
      [5 7]
      [8 9]]

Entrada:

      print(calcular_svd(A))

Salida:

      {'U': array([[-0.14599302, -0.55018941, -0.8221786 ],
       [-0.57456139, -0.62939351,  0.52320456],
       [-0.80533549,  0.5487763 , -0.22423053]]), 's': array([14.9398133 ,  0.89553249]), 'V_T': array([[-0.6333067 , -0.77390091],
       [ 0.77390091, -0.6333067 ]])}

In [ ]:
from numpy.linalg import svd
import numpy as np
#Crea la funcion calcular_svd
def calcular_svd(array1):
  U,s,V_T=np.linalg.svd(array1)
  result={'U':U,'s':s,'V_T':V_T}
  return result






A=np.array([[1,2],[5,7],[8,9]])
print(calcular_svd(A))


{'U': array([[-0.14599302, -0.55018941, -0.8221786 ],
       [-0.57456139, -0.62939351,  0.52320456],
       [-0.80533549,  0.5487763 , -0.22423053]]), 's': array([14.9398133 ,  0.89553249]), 'V_T': array([[-0.6333067 , -0.77390091],
       [ 0.77390091, -0.6333067 ]])}


In [ ]:
#@title Comprueba la funcion calcular_svd
from numpy.linalg import svd
import numpy as np
A_check=np.array([[10,23],[58,71],[89,98],[16,40]])
def check():
  if str(calcular_svd(A_check))=="{'U': array([[-0.14353134,  0.43448506, -0.28421655, -0.84252148],\n       [-0.54635191,  0.04501559, -0.75033941,  0.36941028],\n       [-0.78816521, -0.36517047,  0.4505506 , -0.20603468],\n       [-0.24432346,  0.82209905,  0.391428  ,  0.33353157]]), 's': array([167.79646837,  16.10419829]), 'V_T': array([[-0.63874767, -0.76941628],\n       [-0.76941628,  0.63874767]])}":
    return 'Correcto'
  else:
    return 'Incorrecto'
check()

'Correcto'

##Reconstruir la Matriz dese SVD

Es posible reconstruir la matriz A desde los elementos de las matrices U,sigma y V^T.

Antes hemos dicho que A se puede descomponer en:

      A(m x n)= U (m x m) . Sigma (m x n) . V^T (n x n)

Por lo que si multiplicamos matricialmente U,sigma y V^T volveríamos a obtener A.

Crea la función reconstruir_svd que tome como parámetro una matriz U, una matriz sigma y una matriz V^T y devuelva la matriz resultante.

Ten en cuenta que la matriz sigma obtenida al aplicar la función svd es de tamaño 1 x n y debería ser m x n para poder multiplicarse matricialmente. La función reconstruir_svd debe comprobar las dimensiones de la matriz sigma y corregirlas si no son las adecuadas.

Entrada

      dic=calcular_svd(A)
      print(reconstruir_svd(dic['U'],dic['s'],dic['V_T']))

Salida

      [[1. 2.]
      [5. 7.]
      [8. 9.]]

In [ ]:
from numpy.linalg import svd
import numpy as np
#Crea la funcion reconstruir_svd
def reconstruir_svd(array2,array3,array4):
  D=np.vstack((np.diag(array3),np.zeros((1,array3.shape[0]))))
  result=array2.dot(D).dot(array4)

  return result


dic1=calcular_svd(A)
print(reconstruir_svd(dic1['U'],dic1['s'],dic1['V_T']))


[[1. 2.]
 [5. 7.]
 [8. 9.]]


In [ ]:
#@title Comprueba la funcion reconstruir_svd
A_check2=np.array([[3,5,8,10],[11,13,25,19],[2,6,17,29],[3,5,2,1],[7,9,5,4]],float)
dic_check2=calcular_svd(A_check2)
result=reconstruir_svd(dic_check2['U'],dic_check2['s'],dic_check2['V_T'])
def check2():
  if str(result)==str(A_check2):
    return 'Correcto'
  else:
    return 'Incorrecto'

check2()

'Correcto'

#SVD para Pseudoinversa

Si la matriz es cuadrada es posible calcular la matriz inversa, pero si se trata de una matriz cuadrada (no tiene el mismo numero de filas y columnas) no es posible calcular la matriz inversa.

En cambio si es posible calcular la matriz pseudoinversa, tambien llamada inversa generalizada o inversa de Moore-Penrose, en honor a dos descubridores del método que trabajaron independientes el uno del otro.

El pseudoinverso se denota como A^+, donde A es la matriz que se invierte y + es un superíndice. Para calcularla se aplica la siguiente fórmula:

      A^+ = V . D^+ . U^T

Siendo los SVD U,Sigma y V^T podemos obtener:

* U^T: Calculando la transpuesta de U
* V: calculando la transpuesta de V^T, puesto que como sanes la transpuesta de la transpuesta es la original.
* D^+: se puede calular creando la matriz diagonal sigma y calculando el valor inverso de cada elelemtno de la diagonal.

Crear la función pseuinversa que tomando una matriz como parámetro calcule su pseudoinversa.



In [ ]:
from numpy.linalg import svd
import numpy as np
#Crea la función pseudoinversa

def pseudoinversa(array5):
  U,s,V_T=np.linalg.svd(array5)
  U_T=np.transpose(U)
  V=np.transpose(V_T)
  D_T=np.hstack((np.diag(1/s),np.zeros((2,s.shape[0]))))

  result=V.dot(D_T).dot(U_T)
  return result

A=np.array([[0.1,0.2],[0.3,0.4],[0.5,0.6],[0.7,0.8]])

print(pseudoinversa(A))



[[-1.00000000e+01 -5.00000000e+00  1.42578328e-14  5.00000000e+00]
 [ 8.50000000e+00  4.50000000e+00  5.00000000e-01 -3.50000000e+00]]


In [ ]:
from numpy.linalg import svd
import numpy as np
#@title Comprueba la funcion pseudoinversa
A_check3=np.array([[3,5],[2,7],[9,2],[6,4]])
result=pseudoinversa(A_check3)
def check3():
  if str(result)==str(np.linalg.pinv(A_check3)):
    return 'Correcto'
  else:
    return 'Incorrecto'
check3()

'Correcto'

##SVD para reducir las dimensiones lineales de una matriz

Los datos con un gran número de características, es decir más características (columnas) que observaciones (filas), pueden reducirse a un subconjunto más pequeño de características que sean más relevantes para el problema de predicción.

El resultado es una matriz con un rango inferior que se aproxima a la matriz original.

Para ello, podemos realizar una operación SVD sobre los datos originales y seleccionar los k mayores valores singulares de Sigma. Estas columnas se pueden seleccionar de Sigma y las filas de V^T.

Entonces se puede reconstruir una matriz B aproximada de la matriz A original aplicando la siguiente fórmula:

      B (m x n) = U (m x m) . Sigmak (m x k). V^Tk (k x n)

En el procesamiento del lenguaje natural, este enfoque puede utilizarse en matrices de ocurrencias de palabras o frecuencias de palabras en los documentos (como el que preparaste en el proyecto de Bag of Words) y se denomina análisis semántico latente o indexación semántica latente.

En la práctica podemos utilizar otra matriz aún más simplificada que B, denominada T. Hay dos formas de calcular T:

      T (m x k)= U (m x m). Sigmak (m x k)
      T (m x k)= A (m x n) . V^KT (n x k)

Donde V^KT se calcula realizando la transpuesta al subconjunto de elementos de V^T (k x n) 
Crea la funcion reducir_dimensiones1 que tome como parámetro una matriz y el número de características (columnas, k valores singulares) que se desea tener en cuenta y devuelva la matriz T (m x k) aplicando la primera fórmula y otra función reducir_dimensiones2 que haga lo mismo pero aplicando la segunda fórmula.


In [ ]:
from numpy.linalg import svd
import numpy as np
def reducir_dimensiones1(array6,k1):
  U,s,V_T=np.linalg.svd(array6)
  s_max=s[:k1] #np.array([np.sort(s)[-1-i] for i in range(k1)])
  if array6.shape[0]==s_max.shape[0]:
    s_k=np.vstack((np.diag(s_max),np.zeros((0,s_max.shape[0]))))
  else:
    s_k=np.vstack((np.diag(s_max),np.zeros((1,s_max.shape[0]))))
  
  T=U.dot(s_k)

  return T

#Crea la funcion reducir_dimensiones2
def reducir_dimensiones2(array7,k2):
  U,s,V_T=np.linalg.svd(array7)
  V_T_max=V_T[:k2,:]
  V_kT=np.transpose(V_T_max)

  T=array7.dot(V_kT)

  return T






A=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])

print(reducir_dimensiones1(A,2))

print('.......')

print(reducir_dimensiones2(A,2))



[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
.......
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]


In [ ]:
#@title Comprueba las funciones reducir_dimensiones1 y reducir_dimensiones2 
from numpy.linalg import svd
import numpy as np
A_check4=np.array([[11,32,53,14,35,56,17,38,59,110],[211,612,713,214,615,716,217,618,719,220],[421,622,923,424,625,926,427,628,929,30]])
def check4():
  if str(reducir_dimensiones1(A_check4,3))==str(reducir_dimensiones2(A_check4,3)):
    return 'Correcto'
  else:
    return 'Incorrecto'
check4()

'Correcto'

In [ ]:
#@title Consigue el Token para corregir en Nodd3r:
from numpy.linalg import svd
import numpy as np
import hashlib
A_token1=np.array([[1,3,4],[4,9,5],[1,2,3],[7,8,9]])
A_token2=np.array([[1,3,4,9,10],[4,9,5,7,3],[1,2,3,4,5]])
dic_token=calcular_svd(A_token1)
pwd = hashlib.sha256((str(calcular_svd(A_token1))+str(reducir_dimensiones1(A_token2,2))+str(reconstruir_svd(dic_token['U'],dic_token['s'],dic_token['V_T']))).encode())
#print('El token es:\n',pwd.hexdigest())
if pwd.hexdigest()[0:6] == 'c9fd41':
  print('¡Felicidades! puedes avanzar al siguiente modulo \n El token es: ',pwd.hexdigest())
else:
  print('Hay algún error en el código o tu forma es diferente a la planteada, pregunta por el foro si no lo ves claro.')

¡Felicidades! puedes avanzar al siguiente modulo 
 El token es:  c9fd4113cc831baaac5fae233476c061e1c48b19610472694b729b295d0bc3f4


Una vez que has visto como se calcula manualmente la pseudoinversa y la matriz transformada T para la reducción dimensional de matrices, existen funciones ya predefinidas que facilitan estos procesos.


In [ ]:
from numpy.linalg import svd
import numpy as np
#calcular pseudoinversa

matriz=np.array([[1,3,4,9,10],[4,9,5,7,3],[1,2,3,4,5]])
print('Matriz original:\n', matriz)
print('Matriz pseudoinversa:\n',np.linalg.pinv(matriz))

#calcular T transformada
import sklearn.decomposition as skd
svd = skd.TruncatedSVD(n_components=2)
svd.fit(matriz)
result = svd.transform(matriz)
print('Matriz transformada:\n', result)

Matriz original:
 [[ 1  3  4  9 10]
 [ 4  9  5  7  3]
 [ 1  2  3  4  5]]
Matriz pseudoinversa:
 [[-0.10470085  0.02564103  0.18076923]
 [ 0.00320513  0.09615385 -0.10961538]
 [-0.30662393 -0.03205128  0.68653846]
 [ 0.28525641  0.05769231 -0.55576923]
 [-0.02457265 -0.07051282  0.24038462]]
Matriz transformada:
 [[13.7495653  -4.21808261]
 [12.18995789  5.60351686]
 [ 7.22417326 -1.4271297 ]]
